# Anubistoken <anubistoken.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GA55CDB6EUD6P7VUIVQ5AFFA3CQRVKRNN4KGCM7PZHLFDQTFTECN4EPO"
]

[DOCUMENTATION]
ORG_NAME="Ptahtoken"
ORG_URL="https://ptahtoken.github.io"
ORG_LOGO = "https://ptahtoken.github.io/img/ptah.png"
ORG_OFFICIAL_EMAIL="ptahtoken@gmail.com"
ORG_SUPPORT_EMAIL="ptahtoken@gmail.com"
ORG_TWITTER="0ptahtoken"
ORG_DESCRIPTION="Ptahtoken: Create Value to Meme Coin Space"

[[PRINCIPALS]]
email="ptahtoken@gmail.com"

[[CURRENCIES]]
code = "PTAH"
name = "PTAH"
issuer = "GA55CDB6EUD6P7VUIVQ5AFFA3CQRVKRNN4KGCM7PZHLFDQTFTECN4EPO"
is_asset_anchored=false
display_decimals = 7
desc="This is meme token of PTAH."
image="https://ptahtoken.github.io/img/ptah.png"
conditions="There will only ever be 1 billion PTAH tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
