# fwateam <fwateam.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GCJKAJKSIFMAE6KTHEPUJQQYZ4ZE5FVDO4PG2WDIDWBQENGJCM63FOJE"
]

[DOCUMENTATION]
ORG_NAME="fwateam"
ORG_URL="https://fwateam.github.io"
ORG_LOGO = "https://fwateam.github.io/img/fwa.png"
ORG_OFFICIAL_EMAIL="0xfwateam@gmail.com"
ORG_SUPPORT_EMAIL="0xfwateam@gmail.com"
ORG_TWITTER="0xfwateam"
ORG_DESCRIPTION="fwateam: Create Value to NFT Space"

[[PRINCIPALS]]
email="0xfwateam@gmail.com"

[[CURRENCIES]]
code = "FWA"
name = "FWA"
issuer = "GCJKAJKSIFMAE6KTHEPUJQQYZ4ZE5FVDO4PG2WDIDWBQENGJCM63FOJE"
is_asset_anchored=false
display_decimals = 7
desc="This is token of FWA."
image="https://fwateam.github.io/img/fwa.png"
conditions="There will only ever be 1 billion FWA tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
